name: Move issues into 'Ready for release' when they are closed by a PR

on:
  issues:
    types: [closed]

jobs:
  move-issue-into-ready-for-release:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: GOV.UK Prototype Team Sprintboard
          column: Ready for release
          repo-token: ${{ secrets.GITHUB_TOKEN }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORGANIZATION: alphagov
  PROJECT_NUMBER: 67